# Generated by Django 4.1.1 on 2022-09-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0002_shortenedurl_delete_shortenedurls'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='target_url',
            field=models.URLField(default='http://google.com'),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
