# Generated by Django 4.1.1 on 2022-09-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0003_shortenedurl_target_url_alter_shortenedurl_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='target_url',
            field=models.URLField(default='http://www.google.com'),
        ),
    ]
