# Generated by Django 4.1.1 on 2022-09-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0004_alter_shortenedurl_target_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
